name: Rename package according to repo name

on: [push]

permissions: write-all

jobs:
  rename-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
   
      - name: Run rename
        if: contains(github.event.head_commit.message, 'Initial commit')
        run: |
          echo "Running rename steps..."
          .github/rename.sh "${{ github.repository }}"

      - name: Remove rename workflow
        if: contains(github.event.head_commit.message, 'Initial commit')
        run: rm .github/workflows/rename.yml .github/rename.sh


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          push_options: --force

